name: Build Verbose iOS dylib

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build libhook_verbose.dylib
        run: |
          mkdir -p connect_hook_verbose/output
          clang -dynamiclib -arch arm64 \
            -Iconnect_hook_verbose/fishhook \
            -o connect_hook_verbose/output/libhook_verbose.dylib \
            connect_hook_verbose/connect_hook_verbose.c \
            connect_hook_verbose/fishhook/fishhook.c

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hook-verbose-dylib
          path: connect_hook_verbose/output/
